apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-syncer.fullname" . }}
  labels:
    {{- include "kube-syncer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-syncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-syncer.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: kube-syncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: conf
              mountPath: /etc/kubesync/conf
          env:
            - name: CONFIG_FOLDER
              value: {{ .Values.conf.configFolder }}
      volumes:
        - name: conf
          configMap:
            name: {{ .Values.conf.configMap }}
